import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "tests/**",
      "dist",
      "src-tauri",
      "node_modules",
      // Generated by ts-rs (cargo test) from Rust IPC types — never hand-edited,
      // still type-checked by `tsc` via tsconfig.json's `include`. See
      // src-tauri/crates/core/src/lib.rs (`ts_exports` module) and CLAUDE.md.
      "src/types/generated",
      "src/types/generated.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
);
