pub mod config;
pub mod credentials;
pub mod hash;
pub mod health;
pub mod logging;
pub mod paths;
pub mod power;
pub mod queue;
pub mod rescan;
pub mod stabilize;
pub mod state;
pub mod throttle;
pub mod uploaders;
pub mod watcher;
pub mod worker;

/// Returns the crate's version, as declared in `Cargo.toml`.
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_returns_cargo_package_version() {
        assert_eq!(version(), env!("CARGO_PKG_VERSION"));
    }
}

/// Regenerates the frontend's `src/types/generated.ts` barrel (PLAN.md
/// T-1.4, SPEC.md §7, PRD.md RNF-010).
///
/// `#[ts(export)]` on a type makes `ts-rs` generate its own hidden test that
/// exports just that one type. This module additionally calls
/// [`ts_rs::TS::export_all`] for every *root* type — a type reachable from
/// an IPC command/event boundary — so that its transitive dependencies
/// (nested config/state structs and enums) are exported too, then rewrites
/// `src/types/generated.ts` to re-export whatever `.ts` files exist in the
/// export directory afterwards.
///
/// To add a new IPC type: derive `TS` with `#[ts(export)]` on it as usual,
/// and if it is a *root* (not merely a field of an existing root) add one
/// line to the `export_all_roots!` call below. `cargo test` regenerates the
/// barrel; never hand-edit `src/types/generated.ts`.
#[cfg(test)]
mod ts_exports {
    use std::{fs, path::PathBuf};

    use ts_rs::TS;

    use crate::config::{
        AppConfig, AuthMode, GDriveConfig, NightModeConfig, QosConfig, RetryConfig, S3Config,
        StorageClass, ValidationIssue, WatchConfig,
    };
    use crate::logging::LogLine;
    use crate::state::{
        Destination, JobSide, JobStatus, JobView, ListJobsPage, ListJobsQuery, StatusCounts,
    };

    /// Calls `TS::export_all()` (exports the type + all of its transitive
    /// dependencies) for each listed type, panicking with the type's name on
    /// failure so a broken export points straight at its cause.
    macro_rules! export_all_roots {
        ($($t:ty),+ $(,)?) => {
            $(
                <$t as TS>::export_all()
                    .unwrap_or_else(|e| panic!("ts-rs export_all failed for {}: {e}", stringify!($t)));
            )+
        };
    }

    /// Resolves `TS_RS_EXPORT_DIR` the same way ts-rs does: the env var when
    /// set (via `.cargo/config.toml`), else the crate-local `./bindings`
    /// default.
    fn export_dir() -> PathBuf {
        match std::env::var("TS_RS_EXPORT_DIR") {
            Ok(dir) => PathBuf::from(dir),
            Err(_) => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bindings"),
        }
    }

    #[test]
    fn export_barrel() {
        // One line per IPC root type. Dependencies (e.g. `WatchConfig` under
        // `AppConfig`, `JobStatus` under `JobView`) are pulled in
        // automatically and do not need their own line, but listing them
        // too is harmless (re-exporting is idempotent) and keeps this list
        // resilient to future refactors of who-depends-on-whom.
        export_all_roots!(
            AppConfig,
            WatchConfig,
            S3Config,
            StorageClass,
            GDriveConfig,
            AuthMode,
            NightModeConfig,
            QosConfig,
            RetryConfig,
            ValidationIssue,
            LogLine,
            Destination,
            JobStatus,
            JobSide,
            JobView,
            ListJobsQuery,
            ListJobsPage,
            StatusCounts,
        );

        write_barrel();
    }

    /// Lists every `<Name>.ts` file written by ts-rs into the export dir and
    /// rewrites `src/types/generated.ts` (a sibling of that dir) as a sorted
    /// barrel of `export type { Name } from "./generated/Name"` lines.
    fn write_barrel() {
        let dir = export_dir();
        let read_dir = fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("cannot read ts-rs export dir {}: {e}", dir.display()));

        let mut names: Vec<String> = read_dir
            .filter_map(|entry| entry.ok())
            .filter_map(|entry| {
                let path = entry.path();
                if path.extension().and_then(|ext| ext.to_str()) == Some("ts") {
                    path.file_stem()
                        .and_then(|stem| stem.to_str())
                        .map(String::from)
                } else {
                    None
                }
            })
            .collect();
        names.sort();

        let mut out = String::from("// AUTO-GENERATED by cargo test (ts-rs). Do not edit.\n");
        for name in &names {
            out.push_str(&format!(
                "export type {{ {name} }} from \"./generated/{name}\";\n"
            ));
        }

        let barrel_path = dir
            .parent()
            .unwrap_or_else(|| panic!("ts-rs export dir {} has no parent directory", dir.display()))
            .join("generated.ts");

        fs::write(&barrel_path, out)
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", barrel_path.display()));
    }
}
